Radius=float(input())
Circle=3.14*Radius**2
Side=float(input())
Square=Side**2
Length=float(input())
Breadth=float(input())
Rectangle=Length*Breadth
Base=float(input())
Height=float(input())
Parallelogram=Base*Height
Base1=float(input())
Base2=float(input())
Height1=float(input())
Trapezium=0.5*(Base1+Base2)*Height1
print(Circle)
print(Square)
print(Rectangle)
print(Parallelogram)
print(Trapezium)